# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_minifyhtml_wrappers", use_symbols = TRUE, package_name = "minifyhtml")

#' @docType package
#' @usage NULL
#' @useDynLib minifyhtml, .registration = TRUE
NULL

internal_minify <- function(html, do_not_minify_doctype, ensure_spec_compliant_unquoted_attribute_values, keep_closing_tags, keep_html_and_head_opening_tags, keep_spaces_between_attributes, keep_comments, minify_css, minify_js, remove_bangs, remove_processing_instructions) .Call(wrap__internal_minify, html, do_not_minify_doctype, ensure_spec_compliant_unquoted_attribute_values, keep_closing_tags, keep_html_and_head_opening_tags, keep_spaces_between_attributes, keep_comments, minify_css, minify_js, remove_bangs, remove_processing_instructions)

