# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_minifyhtml_wrappers", use_symbols = TRUE, package_name = "minifyhtml")

#' @docType package
#' @usage NULL
#' @useDynLib minifyhtml, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @param text text
#' @export
minify <- function(text) .Call(wrap__minify, text)

